coverage:
  ignore:
    - "tests/"
    - "**/test_*.py"
  status:
    patch:
      default:
        informational: false
        target: 85%     # New code should have 85% coverage
        threshold: 5%   # Allow up to 5% below the target before failing
    project:
      default:
        informational: false
        target: 45%           # Fail if overall coverage drops below 80%
        threshold: 2%         # Allow 2% decrease from previous coverage