site_name: FDTDX
repo_url: https://github.com/ymahlau/fdtdx
site_url: https://ymahlau.github.io/fdtdx
site_description: A JAX framework for the finite-difference time-domain (FDTD) method for solving Maxwell's equations with a focus on inverse design of photonic devices.
site_author: Yannik Mahlau and Frederik Schubert
edit_uri: edit/main/docs/
repo_name: ymahlau/fdtdx
copyright: Maintained by Yannik Mahlau

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: false
            show_signature: true
            separate_signature: true
            #show_bases: true
            merge_init_into_class: true
            # inherited_members: true
            group_by_category: true
            show_category_heading: true
            docstring_style: google
  - mkdocs-jupyter:
      include: ["docs/notebooks/*.ipynb"]
  - awesome-nav

theme:
  name: readthedocs
  logo: img/logo.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences