flatten_single_child_sections: false 

preserve_directory_names: true

sort:
  direction: asc 
  type: natural 
  by: filename 
  sections: last 
  ignore_case: true

nav:
  - Home: index.md
  - Tutorials:
    - JAX in FDTDX: tutorials/jax_introduction.md
    - Object Placement: tutorials/object_placement.md
    - Materials Guide: tutorials/materials.md
    - Fabrication Constraints: tutorials/parameter_mapping.md
    - Interface Compression: tutorials/interface_compression.md
  - API Reference:
    - Public:
      - "api/public/*.md"
      # - Simulation Objects:
      #   - Boundaries: api/public/objects/boundaries.md
      #   - Detectors: api/public/objects/detectors.md
      #   - Device: api/public/objects/device.md
      #   - Objects: api/public/objects/object.md
      #   - Sources: api/public/objects/sources.md
      #   - Static Material: api/public/objects/static_material.md
      # - FDTD: api/public/fdtd.md
      # - Config: api/public/config.md
      # - Constants: api/public/constants.md
      # - Interfaces: api/public/interfaces.md
      # - Materials: api/public/materials.md
      # - Typing: api/public/typing.md
      # - Utils: api/public/utils.md
      # - Core: api/public/core.md
    - Internal:
      - "api/internal/*.md"
    
  